export interface SampleProduct {
  id: string;
  title: string;
  price: number;
  originalPrice?: number;
  condition: "Brand New" | "Used - Like New" | "Used - Good" | "Used - Fair" | "Refurbished";
  category: string;
  subcategory: string;
  description: string;
  specifications: Record<string, string>;
  images: number;
  location: { county: string; town: string };
  seller: {
    id: string;
    name: string;
    verified: boolean;
    rating: number;
    reviews: number;
    products: number;
    sales: number;
    responseRate: string;
    responseTime: string;
    memberSince: string;
  };
  escrowProtected: boolean;
  deliveryAvailable: boolean;
  negotiable: boolean;
  views: number;
  favorites: number;
  postedAt: string;
  status: "active" | "sold" | "pending" | "featured";
}

export const SAMPLE_PRODUCTS: SampleProduct[] = [
  {
    id: "p1",
    title: "HP EliteBook 840 G3",
    price: 22000,
    originalPrice: 28000,
    condition: "Used - Good",
    category: "electronics",
    subcategory: "laptops",
    description: "Clean and reliable business laptop suitable for students, office work, programming, browsing and freelancing. Comes with original charger. Battery lasts 4+ hours.",
    specifications: {
      Brand: "HP",
      Model: "EliteBook 840 G3",
      Processor: "Intel Core i7-6600U",
      RAM: "8GB DDR4",
      Storage: "256GB SSD",
      "Screen Size": "14 inch",
      Resolution: "1920x1080",
      "Operating System": "Windows 11 Pro",
      GPU: "Intel HD 520",
      Battery: "Good",
    },
    images: 4,
    location: { county: "Nairobi", town: "Westlands" },
    seller: {
      id: "s1",
      name: "TechZone Kenya",
      verified: true,
      rating: 4.8,
      reviews: 245,
      products: 128,
      sales: 734,
      responseRate: "98%",
      responseTime: "Within 10 minutes",
      memberSince: "2023",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: true,
    views: 1247,
    favorites: 89,
    postedAt: "2 days ago",
    status: "active",
  },
  {
    id: "p2",
    title: "iPhone 15 Pro Max 256GB",
    price: 142000,
    originalPrice: 165000,
    condition: "Brand New",
    category: "phones-tablets",
    subcategory: "iphones",
    description: "Brand new, sealed box iPhone 15 Pro Max. Natural Titanium color. 100% battery health. Apple warranty included. Face ID enabled.",
    specifications: {
      Model: "iPhone 15 Pro Max",
      Storage: "256GB",
      Color: "Natural Titanium",
      "Battery Health": "100%",
      Camera: "48MP Triple Camera",
      Display: "6.7 inch Super Retina XDR",
      Condition: "Brand New",
      Warranty: "1 Year Apple Warranty",
      "Face ID": "Yes",
    },
    images: 5,
    location: { county: "Nairobi", town: "CBD" },
    seller: {
      id: "s2",
      name: "AppleStore KE",
      verified: true,
      rating: 4.9,
      reviews: 189,
      products: 45,
      sales: 567,
      responseRate: "99%",
      responseTime: "Within 5 minutes",
      memberSince: "2022",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: false,
    views: 2341,
    favorites: 156,
    postedAt: "1 day ago",
    status: "active",
  },
  {
    id: "p3",
    title: "Samsung Galaxy S24 Ultra 512GB",
    price: 165000,
    originalPrice: 185000,
    condition: "Brand New",
    category: "phones-tablets",
    subcategory: "samsung",
    description: "Factory unlocked Samsung Galaxy S24 Ultra. Titanium Black. S Pen included. AI features enabled. Dual SIM.",
    specifications: {
      Brand: "Samsung",
      Model: "Galaxy S24 Ultra",
      Storage: "512GB",
      RAM: "12GB",
      Camera: "200MP Quad Camera",
      Display: "6.8 inch Dynamic AMOLED 2X",
      Condition: "Brand New",
      Warranty: "1 Year Samsung Warranty",
    },
    images: 4,
    location: { county: "Nairobi", town: "Karen" },
    seller: {
      id: "s3",
      name: "Samsung Hub KE",
      verified: true,
      rating: 4.7,
      reviews: 132,
      products: 67,
      sales: 423,
      responseRate: "95%",
      responseTime: "Within 15 minutes",
      memberSince: "2023",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: false,
    views: 983,
    favorites: 67,
    postedAt: "3 days ago",
    status: "active",
  },
  {
    id: "p4",
    title: "Toyota Fielder 2019",
    price: 1850000,
    originalPrice: 2100000,
    condition: "Used - Like New",
    category: "vehicles",
    subcategory: "cars",
    description: "Toyota Fielder 2019 model. Low mileage, single owner. Well maintained with full service history. Original paint. AA inspected.",
    specifications: {
      Make: "Toyota",
      Model: "Fielder",
      Year: "2019",
      Mileage: "45,000 km",
      Engine: "1500cc",
      Transmission: "Automatic",
      Fuel: "Petrol",
      Drive: "2WD",
      Condition: "Used",
      Registration: "KDE****X",
    },
    images: 8,
    location: { county: "Nairobi", town: "Langata" },
    seller: {
      id: "s4",
      name: "AutoHub Kenya",
      verified: true,
      rating: 4.6,
      reviews: 89,
      products: 34,
      sales: 156,
      responseRate: "92%",
      responseTime: "Within 30 minutes",
      memberSince: "2022",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: true,
    views: 3456,
    favorites: 234,
    postedAt: "5 days ago",
    status: "active",
  },
  {
    id: "p5",
    title: "Nike Air Max 90 - White/Black",
    price: 12500,
    originalPrice: 15000,
    condition: "Brand New",
    category: "fashion",
    subcategory: "shoes",
    description: "Authentic Nike Air Max 90. White and black colorway. Size 42 EU. Brand new in box with tags. 100% genuine.",
    specifications: {
      Brand: "Nike",
      Size: "42 EU",
      Color: "White/Black",
      Material: "Leather and Mesh",
      Condition: "Brand New",
    },
    images: 4,
    location: { county: "Nairobi", town: "CBD" },
    seller: {
      id: "s5",
      name: "SneakerVault KE",
      verified: true,
      rating: 4.5,
      reviews: 167,
      products: 89,
      sales: 445,
      responseRate: "96%",
      responseTime: "Within 20 minutes",
      memberSince: "2023",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: false,
    views: 654,
    favorites: 45,
    postedAt: "1 day ago",
    status: "active",
  },
  {
    id: "p6",
    title: "Sony WH-1000XM5 Headphones",
    price: 38000,
    originalPrice: 45000,
    condition: "Brand New",
    category: "electronics",
    subcategory: "audio-equipment",
    description: "Industry-leading noise cancelling headphones. Silver color. 30-hour battery. Multipoint connection. Hi-Res Audio.",
    specifications: {
      Brand: "Sony",
      Model: "WH-1000XM5",
      Type: "Over-Ear Wireless",
      "Battery Life": "30 hours",
      Condition: "Brand New",
      Warranty: "1 Year",
    },
    images: 3,
    location: { county: "Nairobi", town: "Westlands" },
    seller: {
      id: "s6",
      name: "AudioPro KE",
      verified: true,
      rating: 4.8,
      reviews: 98,
      products: 56,
      sales: 312,
      responseRate: "97%",
      responseTime: "Within 10 minutes",
      memberSince: "2023",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: true,
    views: 445,
    favorites: 34,
    postedAt: "4 days ago",
    status: "active",
  },
  {
    id: "p7",
    title: "Dell 27\" 4K Monitor",
    price: 45000,
    originalPrice: 55000,
    condition: "Used - Like New",
    category: "electronics",
    subcategory: "monitors",
    description: "Dell UltraSharp 27\" 4K USB-C Monitor. Excellent for design and coding. Includes all cables and stand.",
    specifications: {
      Brand: "Dell",
      Model: "U2723QE",
      "Screen Size": "27 inch",
      Resolution: "3840x2160 (4K)",
      Condition: "Used - Like New",
    },
    images: 3,
    location: { county: "Nairobi", town: "Kilimani" },
    seller: {
      id: "s1",
      name: "TechZone Kenya",
      verified: true,
      rating: 4.8,
      reviews: 245,
      products: 128,
      sales: 734,
      responseRate: "98%",
      responseTime: "Within 10 minutes",
      memberSince: "2023",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: true,
    views: 312,
    favorites: 23,
    postedAt: "1 week ago",
    status: "active",
  },
  {
    id: "p8",
    title: "Italian Leather Sofa Set",
    price: 85000,
    originalPrice: 95000,
    condition: "Brand New",
    category: "home-furniture",
    subcategory: "sofas",
    description: "3-seater + 2-seater + single. Dark brown genuine leather. Premium quality. Free delivery within Nairobi.",
    specifications: {
      Brand: "Italian Design",
      Type: "3-Piece Set",
      Material: "Genuine Leather",
      Color: "Dark Brown",
      Condition: "Brand New",
    },
    images: 6,
    location: { county: "Nairobi", town: "Industrial Area" },
    seller: {
      id: "s7",
      name: "FurniWorld KE",
      verified: true,
      rating: 4.4,
      reviews: 78,
      products: 45,
      sales: 189,
      responseRate: "90%",
      responseTime: "Within 1 hour",
      memberSince: "2022",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: true,
    views: 234,
    favorites: 18,
    postedAt: "3 days ago",
    status: "active",
  },
  {
    id: "p9",
    title: "MacBook Pro 14\" M3 Max",
    price: 285000,
    originalPrice: 320000,
    condition: "Brand New",
    category: "electronics",
    subcategory: "laptops",
    description: "Brand new, sealed MacBook Pro 14 inch with M3 Max chip. 36GB RAM, 1TB SSD. Space Black. Apple warranty included.",
    specifications: {
      Brand: "Apple",
      Model: "MacBook Pro 14\" M3 Max",
      Processor: "Apple M3 Max",
      RAM: "36GB",
      Storage: "1TB SSD",
      "Screen Size": "14 inch",
      Resolution: "3024x1964",
      "Operating System": "macOS Sonoma",
      GPU: "M3 Max 30-core GPU",
      Battery: "Excellent",
    },
    images: 5,
    location: { county: "Nairobi", town: "Westlands" },
    seller: {
      id: "s2",
      name: "AppleStore KE",
      verified: true,
      rating: 4.9,
      reviews: 189,
      products: 45,
      sales: 567,
      responseRate: "99%",
      responseTime: "Within 5 minutes",
      memberSince: "2022",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: false,
    views: 1247,
    favorites: 89,
    postedAt: "1 day ago",
    status: "active",
  },
  {
    id: "p10",
    title: "Subaru Forester 2020",
    price: 3200000,
    condition: "Used - Good",
    category: "vehicles",
    subcategory: "cars",
    description: "Subaru Forester 2020 XT. Turbocharged. EyeSight safety. All-wheel drive. Low mileage. Full service history.",
    specifications: {
      Make: "Subaru",
      Model: "Forester XT",
      Year: "2020",
      Mileage: "38,000 km",
      Engine: "1800cc Turbo",
      Transmission: "CVT",
      Fuel: "Petrol",
      Drive: "AWD",
      Condition: "Used",
      Registration: "KDG****M",
    },
    images: 10,
    location: { county: "Mombasa", town: "Nyali" },
    seller: {
      id: "s4",
      name: "AutoHub Kenya",
      verified: true,
      rating: 4.6,
      reviews: 89,
      products: 34,
      sales: 156,
      responseRate: "92%",
      responseTime: "Within 30 minutes",
      memberSince: "2022",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: true,
    views: 4567,
    favorites: 312,
    postedAt: "2 days ago",
    status: "active",
  },
  {
    id: "p11",
    title: "50 Acres Farmland - Nakuru",
    price: 4500000,
    condition: "Brand New",
    category: "property",
    subcategory: "land",
    description: "50 acres of prime farmland in Nakuru County. fertile soil, water available, road access, title deed ready. Perfect for farming or investment.",
    specifications: {
      Type: "Farmland",
      Size: "50 Acres",
      Title: "Freehold",
      Water: "Available",
      Road: "Tarmac Access",
      Condition: "New",
    },
    images: 6,
    location: { county: "Nakuru", town: "Naivasha" },
    seller: {
      id: "s8",
      name: "Kenya Lands KE",
      verified: true,
      rating: 4.3,
      reviews: 34,
      products: 12,
      sales: 45,
      responseRate: "88%",
      responseTime: "Within 2 hours",
      memberSince: "2023",
    },
    escrowProtected: true,
    deliveryAvailable: false,
    negotiable: true,
    views: 789,
    favorites: 45,
    postedAt: "1 week ago",
    status: "active",
  },
  {
    id: "p12",
    title: "Ladies Genuine Leather Handbag",
    price: 4500,
    originalPrice: 6000,
    condition: "Brand New",
    category: "fashion",
    subcategory: "bags",
    description: "Genuine leather ladies handbag. Multiple compartments. Premium quality. Available in black, brown, and red.",
    specifications: {
      Brand: "Premium",
      Type: "Handbag",
      Material: "Genuine Leather",
      Color: "Black/Brown/Red",
      Condition: "Brand New",
    },
    images: 4,
    location: { county: "Nairobi", town: "CBD" },
    seller: {
      id: "s9",
      name: "Fashion Hub KE",
      verified: false,
      rating: 4.2,
      reviews: 56,
      products: 78,
      sales: 234,
      responseRate: "85%",
      responseTime: "Within 1 hour",
      memberSince: "2024",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: true,
    views: 345,
    favorites: 28,
    postedAt: "3 days ago",
    status: "active",
  },
  {
    id: "p13",
    title: "PS5 Console Bundle",
    price: 72000,
    originalPrice: 80000,
    condition: "Brand New",
    category: "electronics",
    subcategory: "gaming",
    description: "PlayStation 5 Disc Edition. Includes 2 controllers, 3 games (Spider-Man 2, FIFA 24, GTA V), and extra headset.",
    specifications: {
      Brand: "Sony",
      Model: "PS5 Disc Edition",
      Type: "Console Bundle",
      Storage: "825GB SSD",
      Condition: "Brand New",
      Warranty: "1 Year",
    },
    images: 5,
    location: { county: "Nairobi", town: "Kasarani" },
    seller: {
      id: "s10",
      name: "GameZone KE",
      verified: true,
      rating: 4.7,
      reviews: 112,
      products: 34,
      sales: 289,
      responseRate: "94%",
      responseTime: "Within 15 minutes",
      memberSince: "2023",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: false,
    views: 567,
    favorites: 67,
    postedAt: "2 days ago",
    status: "active",
  },
  {
    id: "p14",
    title: "Web Development Services",
    price: 50000,
    condition: "Brand New",
    category: "services",
    subcategory: "it-services",
    description: "Professional web development services. React, Next.js, Node.js. Full-stack development. Responsive design. SEO optimized. 30-day support.",
    specifications: {
      Type: "Web Development",
      Technology: "React, Next.js, Node.js",
      Duration: "2-4 weeks",
      Support: "30 days",
      Condition: "New",
    },
    images: 2,
    location: { county: "Nairobi", town: "Westlands" },
    seller: {
      id: "s11",
      name: "DevStudio KE",
      verified: true,
      rating: 4.9,
      reviews: 67,
      products: 8,
      sales: 123,
      responseRate: "100%",
      responseTime: "Within 5 minutes",
      memberSince: "2022",
    },
    escrowProtected: true,
    deliveryAvailable: false,
    negotiable: true,
    views: 234,
    favorites: 19,
    postedAt: "5 days ago",
    status: "active",
  },
  {
    id: "p15",
    title: "Infinix Hot 40 Pro",
    price: 18500,
    condition: "Brand New",
    category: "phones-tablets",
    subcategory: "android-phones",
    description: "Infinix Hot 40 Pro. 256GB storage, 8GB RAM. 108MP camera. 5000mAh battery. Fast charging. Dual SIM.",
    specifications: {
      Brand: "Infinix",
      Model: "Hot 40 Pro",
      Storage: "256GB",
      RAM: "8GB",
      Battery: "5000mAh",
      Camera: "108MP",
      Display: "6.78 inch AMOLED",
      Condition: "Brand New",
      Warranty: "1 Year",
    },
    images: 3,
    location: { county: "Nairobi", town: "Eastleigh" },
    seller: {
      id: "s12",
      name: "PhoneWorld KE",
      verified: true,
      rating: 4.4,
      reviews: 178,
      products: 56,
      sales: 456,
      responseRate: "93%",
      responseTime: "Within 10 minutes",
      memberSince: "2023",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: true,
    views: 456,
    favorites: 34,
    postedAt: "1 day ago",
    status: "active",
  },
  {
    id: "p16",
    title: "Samsung 55\" Smart TV",
    price: 65000,
    originalPrice: 78000,
    condition: "Brand New",
    category: "electronics",
    subcategory: "tvs",
    description: "Samsung 55 inch Crystal UHD 4K Smart TV. HDR10+. Voice assistant. 3 HDMI ports. Wall mount included.",
    specifications: {
      Brand: "Samsung",
      Model: "CU8000",
      "Screen Size": "55 inch",
      Resolution: "3840x2160 (4K)",
      "Smart TV": "Yes - Tizen OS",
      Condition: "Brand New",
      Warranty: "2 Years",
    },
    images: 4,
    location: { county: "Nairobi", town: "Luthuli Avenue" },
    seller: {
      id: "s3",
      name: "Samsung Hub KE",
      verified: true,
      rating: 4.7,
      reviews: 132,
      products: 67,
      sales: 423,
      responseRate: "95%",
      responseTime: "Within 15 minutes",
      memberSince: "2023",
    },
    escrowProtected: true,
    deliveryAvailable: true,
    negotiable: false,
    views: 345,
    favorites: 28,
    postedAt: "3 days ago",
    status: "active",
  },
];

export function getProductsByCategory(categorySlug: string): SampleProduct[] {
  return SAMPLE_PRODUCTS.filter((p) => p.category === categorySlug);
}

export function getProductById(id: string): SampleProduct | undefined {
  return SAMPLE_PRODUCTS.find((p) => p.id === id);
}

export function searchProducts(query: string): SampleProduct[] {
  const q = query.toLowerCase();
  return SAMPLE_PRODUCTS.filter(
    (p) =>
      p.title.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.subcategory.toLowerCase().includes(q) ||
      p.seller.name.toLowerCase().includes(q) ||
      p.location.county.toLowerCase().includes(q) ||
      p.location.town.toLowerCase().includes(q)
  );
}

export function formatPrice(price: number): string {
  return `KSh ${price.toLocaleString()}`;
}

export function getConditionColor(condition: string): string {
  if (condition === "Brand New") return "text-emerald-400 bg-emerald-400/10";
  if (condition.startsWith("Used")) return "text-amber-400 bg-amber-400/10";
  return "text-blue-400 bg-blue-400/10";
}
